# Generated by Django 4.1 on 2022-08-06 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('depart', models.CharField(max_length=200)),
                ('cab', models.CharField(max_length=200)),
                ('startwork', models.DateTimeField()),
                ('endwork', models.DateTimeField()),
                ('vacation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('depart', models.CharField(max_length=200)),
                ('chamber', models.CharField(max_length=200)),
                ('starttreament', models.DateTimeField()),
                ('endtreament', models.DateTimeField()),
                ('checkout', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.doctors')),
                ('pacient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pacient')),
            ],
        ),
    ]
